### ISSUE TITLE
Why use "firebase/php-jwt": "^3.0"

### ISSUE THREAD

**Issue by Blaztix** [byjg/jwt-wrapper#1]
currently `firebase/php-jwt` have a version 5.0.0 (in 2017)

**Comment by byjg** [comment]
Hello, 

The newer JwtWrapper does not break compatibility, so I think is fine do it. 

I created some unit tests for the JwtWrapper just to guarantee everything is fine and assigned temporally the version `2.0.0.x-dev`.

I will create the final release after upgrade other components I have.

**Comment by byjg** [comment]
Done. Composer version 2.0.0.
